import { QuizSeed } from './types';

/**
 * Rapid-recall bank. Every question is one I would actually use as a warm-up
 * or a probe in a Senior/Lead Node backend loop — the wrong answers are the
 * plausible misconceptions, not filler.
 */
const q = (
  id: string,
  topic: string,
  question: string,
  options: string[],
  answerIndex: number,
  explanation: string,
  ref = '',
  difficulty: 'easy' | 'medium' | 'hard' = 'medium',
): QuizSeed => ({ id, topic, question, options, answerIndex, explanation, ref, difficulty });

export const quiz: QuizSeed[] = [
  // ------------------------------------------------ JavaScript / TypeScript
  q('js-1', 'JavaScript / TypeScript',
    'In which event-loop phase do `process.nextTick` callbacks run?',
    ['The timers phase', 'Between every phase, before promise microtasks', 'The check phase, after setImmediate', 'The poll phase only'],
    1,
    'nextTick has its own queue that drains between phases and BEFORE the promise microtask queue. Starving it with recursive nextTick calls blocks the loop entirely.',
    'phase-1-core-programming/02-nodejs-fundamentals.md'),
  q('js-2', 'JavaScript / TypeScript',
    'What does `Promise.allSettled` give you that `Promise.all` does not?',
    ['Faster resolution', 'Results for every promise, including rejected ones, without short-circuiting', 'Automatic retries', 'Sequential execution'],
    1,
    'allSettled always resolves with an array of {status, value|reason}. Use it for fan-out where one failing call should not discard the other results.'),
  q('js-3', 'JavaScript / TypeScript',
    'Which TypeScript construct best models "either a success with data or a failure with an error code"?',
    ['An interface with optional fields', 'A discriminated union on a literal `kind` field', '`any`', 'An enum'],
    1,
    'A discriminated union lets the compiler narrow exhaustively. Optional fields allow illegal states like both data and error present at once.',
    'phase-1-core-programming/01-javascript-typescript-deep-dive.md'),
  q('js-4', 'JavaScript / TypeScript',
    'Why can a `WeakMap` key be garbage collected while a `Map` key cannot?',
    ['WeakMap is faster', 'WeakMap holds weak references, so an entry does not keep its key alive', 'WeakMap has a size limit', 'Map keys are frozen'],
    1,
    'That is why WeakMap is the right cache when the key is an object whose lifetime you do not control — it prevents the classic per-request cache memory leak.'),
  q('js-5', 'JavaScript / TypeScript',
    'What is the practical difference between `unknown` and `any`?',
    ['None', '`unknown` must be narrowed before use; `any` disables checking entirely', '`unknown` is slower', '`any` is deprecated'],
    1,
    '`unknown` is the type-safe top type. Using it at trust boundaries (parsed JSON, request bodies) forces you to validate before use.'),
  q('js-6', 'JavaScript / TypeScript',
    'An `await` inside a `for...of` loop over 1000 API calls does what?',
    ['Runs all 1000 concurrently', 'Runs them strictly one at a time', 'Batches them automatically', 'Throws on the first rejection only'],
    1,
    'Sequential, and usually a performance bug. Use Promise.all for unbounded concurrency or a concurrency pool when the downstream is rate limited.',
    'practice/async-pool'),
  q('js-7', 'JavaScript / TypeScript',
    'What does an unhandled promise rejection do in Node 20 by default?',
    ['Logs a warning and continues', 'Terminates the process', 'Retries the promise', 'Is silently ignored'],
    1,
    'Since Node 15 the default is `--unhandled-rejections=throw`, which crashes the process. Relying on the old warning behaviour is a production hazard.'),
  q('js-8', 'JavaScript / TypeScript',
    'Which is true of `Object.freeze`?',
    ['It deep-freezes the whole object graph', 'It is shallow — nested objects stay mutable', 'It prevents reads', 'It works only on arrays'],
    1,
    'Shallow. Deep immutability needs a recursive freeze or a structural-sharing library.'),

  // ------------------------------------------------ Node.js
  q('node-1', 'Node.js',
    'The event loop poll phase is blocked for 300ms by a JSON.parse of a huge payload. What is the user-visible effect?',
    ['Only that request is slow', 'Every in-flight request on that instance is delayed by up to 300ms', 'Node spawns a thread automatically', 'The GC compensates'],
    1,
    'Node is single-threaded for JS. One CPU-bound operation stalls every connection on the process — the reason big parses belong in a worker thread or a stream.',
    'phase-1-core-programming/02-nodejs-fundamentals.md'),
  q('node-2', 'Node.js',
    'When should you prefer `worker_threads` over `cluster`?',
    ['Always', 'For CPU-bound work inside one process, sharing memory via SharedArrayBuffer', 'For handling more HTTP connections', 'For scheduled jobs'],
    1,
    'cluster forks processes to use more cores for I/O-bound request handling. worker_threads is for CPU-bound work with cheap data sharing.'),
  q('node-3', 'Node.js',
    'What is backpressure in a Node stream?',
    ['A retry mechanism', 'The signal that a writable consumer cannot keep up, so the producer should pause', 'A compression setting', 'An error event'],
    1,
    '`writable.write()` returning false means "stop until drain". Ignoring it grows an unbounded in-memory buffer — a very common OOM cause. `pipeline()` handles it for you.'),
  q('node-4', 'Node.js',
    'Which pair correctly describes `setImmediate` vs `setTimeout(fn, 0)`?',
    ['Identical', 'setImmediate runs in the check phase; setTimeout(0) in the timers phase, so ordering from the main module is nondeterministic', 'setTimeout always runs first', 'setImmediate is deprecated'],
    1,
    'Inside an I/O callback setImmediate always fires first. From the main module the order depends on process startup timing.'),
  q('node-5', 'Node.js',
    'A graceful shutdown on SIGTERM should, at minimum:',
    ['Call process.exit(0) immediately', 'Stop accepting new connections, drain in-flight requests, close DB/broker connections, then exit with a timeout guard', 'Restart the process', 'Flush stdout only'],
    1,
    'Without draining you drop in-flight requests on every deploy. The timeout guard prevents a hung connection from blocking the rollout forever.'),
  q('node-6', 'Node.js',
    'You suspect a memory leak in production. What is the most direct evidence?',
    ['Rising CPU', 'Comparing two heap snapshots and finding a retained-object class that keeps growing', 'Increasing request latency', 'Log volume'],
    1,
    'Two snapshots plus a diff on retained size names the culprit. Rising RSS alone can just be heap growth the GC has not reclaimed yet.'),
  q('node-7', 'Node.js',
    'What does `--max-old-space-size` control?',
    ['Total process memory', 'The V8 old-generation heap limit', 'Stack size', 'Number of workers'],
    1,
    'It bounds the old-space heap. Setting it above the container memory limit gets you OOMKilled by the kernel instead of a clean V8 heap error.'),
  q('node-8', 'Node.js',
    'Why is `crypto.randomBytes` preferable to `Math.random` for tokens?',
    ['It is faster', 'Math.random is not cryptographically secure and is predictable from observed output', 'It returns strings', 'It is synchronous'],
    1,
    'Math.random uses a fast non-cryptographic PRNG. Session tokens, password resets and idempotency keys all need a CSPRNG.'),

  // ------------------------------------------------ NestJS
  q('nest-1', 'NestJS',
    'Which runs FIRST in the NestJS request pipeline?',
    ['Interceptor', 'Middleware', 'Guard', 'Pipe'],
    1,
    'Middleware → Guards → Interceptors (pre) → Pipes → Handler → Interceptors (post) → Exception filters. Knowing the order is a standard probe.',
    'phase-1-core-programming/03-nestjs-mastery.md'),
  q('nest-2', 'NestJS',
    'What is the correct place for authorisation logic?',
    ['A pipe', 'A guard', 'An interceptor', 'A middleware'],
    1,
    'Guards answer "may this request proceed?" and have access to the execution context. Pipes transform and validate input; interceptors wrap the response.'),
  q('nest-3', 'NestJS',
    'What is the cost of a `REQUEST`-scoped provider?',
    ['None', 'The whole injection subtree is instantiated per request, which hurts throughput', 'It disables DI', 'It forces synchronous handlers'],
    1,
    'Request scope bubbles up — every provider that depends on it also becomes request-scoped. Use an AsyncLocalStorage-based context instead when you only need per-request data.'),
  q('nest-4', 'NestJS',
    'Circular dependency between two providers is best resolved with:',
    ['Making one a singleton', '`forwardRef()`, and ideally by extracting the shared logic into a third module', 'Global providers', 'Removing the constructor'],
    1,
    'forwardRef makes it work; the extraction makes it right. Say both — the second answer is the senior one.'),
  q('nest-5', 'NestJS',
    'For a NestJS service that must publish an event only if a DB write commits, use:',
    ['A try/catch around both', 'The transactional outbox pattern — write the event to an outbox table in the same transaction, relay it asynchronously', 'A retry decorator', 'A global exception filter'],
    1,
    'This is the dual-write problem. Outbox is the standard answer and shows you have hit the failure in production.',
    'phase-2-apis-realtime-systems/04-event-driven-architecture.md'),
  q('nest-6', 'NestJS',
    'Best way to validate incoming DTOs?',
    ['Manual if-checks in the controller', 'A global ValidationPipe with class-validator decorators and `whitelist: true`', 'Trust the client', 'A guard'],
    1,
    '`whitelist: true` strips unknown properties, which also blocks mass-assignment attacks.'),
  q('nest-7', 'NestJS',
    'For unit-testing a service that depends on a repository, you should:',
    ['Spin up a real database', 'Provide a mock via the testing module\'s custom provider token', 'Skip the test', 'Use the production repository'],
    1,
    'Mock at the module boundary. Save the real database for integration tests with testcontainers.'),

  // ------------------------------------------------ System Design
  q('sd-1', 'System Design',
    'Roughly how many requests per second is 100 million requests per day?',
    ['~120/s', '~1,200/s', '~12,000/s', '~120,000/s'],
    1,
    '100M / 86,400 ≈ 1,157/s average. Peak is usually 2-3x that. Being fast and confident with this arithmetic buys you enormous credibility.',
    'phase-5-system-design/01-system-design-fundamentals.md'),
  q('sd-2', 'System Design',
    'What should you do in the first five minutes of a design round?',
    ['Draw the architecture', 'Clarify functional and non-functional requirements and agree on scale numbers', 'Choose a database', 'Discuss sharding'],
    1,
    'Candidates who draw boxes in minute two nearly always design the wrong system. Requirements first, always.'),
  q('sd-3', 'System Design',
    'A read-heavy service with a 95% cache hit rate loses its cache. What happens?',
    ['5% more database load', 'Roughly 20x database load — usually an outage', 'Nothing, the CDN absorbs it', 'Latency improves'],
    1,
    'Going from 5% to 100% of reads hitting the database is a 20x multiplier. This is why cache warming and request coalescing matter.',
    'phase-4-cloud-infrastructure/07-performance-engineering.md'),
  q('sd-4', 'System Design',
    'Consistent hashing exists primarily to:',
    ['Make hashing faster', 'Minimise how many keys move when a node is added or removed', 'Guarantee uniqueness', 'Encrypt keys'],
    1,
    'With modulo hashing, adding one node remaps almost every key. Consistent hashing moves roughly 1/N. Virtual nodes then even out the distribution.'),
  q('sd-5', 'System Design',
    'When is a CDN NOT the right answer?',
    ['Static assets', 'Highly personalised, per-user dynamic responses', 'Video segments', 'Public API responses with long TTLs'],
    1,
    'Per-user content has a cache hit rate near zero at the edge. Edge compute or regional caching is the alternative.'),
  q('sd-6', 'System Design',
    'Which write pattern gives the strongest durability guarantee to the client?',
    ['Write-behind (async flush)', 'Write-through — write cache and store synchronously before acknowledging', 'Fire and forget', 'Cache-aside with TTL'],
    1,
    'Write-behind is faster but loses data on a crash between acknowledge and flush. State the trade-off explicitly.'),
  q('sd-7', 'System Design',
    'The single most useful sentence in a design round is:',
    ['"I would use microservices."', '"Here is the trade-off, and here is why I chose this side of it."', '"That depends."', '"We would need more data."'],
    1,
    'Senior interviews grade reasoning, not recall. Name the alternative you rejected and why.'),
  q('sd-8', 'System Design',
    'Approximate latency of a round trip within the same datacentre?',
    ['~0.5 µs', '~0.5 ms', '~5 ms', '~50 ms'],
    1,
    'Same-DC RTT is roughly half a millisecond; cross-continent is 100-150ms. These numbers anchor every capacity argument you make.'),

  // ------------------------------------------------ PostgreSQL
  q('pg-1', 'PostgreSQL',
    'Given `WHERE tenant_id = $1 AND created_at > $2`, the best index is:',
    ['Two separate single-column indexes', 'A composite index on (tenant_id, created_at)', 'An index on created_at only', 'A hash index on tenant_id'],
    1,
    'The composite matches the equality-then-range shape. Column ORDER matters: equality columns first.',
    'phase-3-databases-data/01-postgresql-deep-dive.md'),
  q('pg-2', 'PostgreSQL',
    'What does MVCC mean for long-running read transactions?',
    ['They block writers', 'They hold back vacuum, causing table and index bloat', 'They speed up writes', 'They force serialisable isolation'],
    1,
    'An old snapshot prevents cleanup of dead tuples. This is the real-world cause of mysterious table bloat on analytics replicas.'),
  q('pg-3', 'PostgreSQL',
    'READ COMMITTED (the Postgres default) permits which anomaly?',
    ['Dirty reads', 'Non-repeatable reads and phantom reads', 'Lost updates only', 'None'],
    1,
    'Postgres never allows dirty reads at any level. READ COMMITTED does allow the same query to see different rows within one transaction.'),
  q('pg-4', 'PostgreSQL',
    'In EXPLAIN ANALYZE, a Seq Scan on a large table with a selective filter usually means:',
    ['The query is optimal', 'A missing or unusable index, or stale statistics', 'The table is locked', 'The planner is broken'],
    1,
    'Check for a function wrapping the column (which defeats the index), type mismatch, or an ANALYZE that has not run.'),
  q('pg-5', 'PostgreSQL',
    'To search inside a JSONB column efficiently you want:',
    ['A B-tree index', 'A GIN index', 'A BRIN index', 'No index — JSONB is always fast'],
    1,
    'GIN indexes the contents. B-tree only helps for whole-value equality.'),
  q('pg-6', 'PostgreSQL',
    'Two transactions update the same two rows in opposite order. The result is:',
    ['A deadlock, one transaction is aborted', 'Both succeed', 'Silent corruption', 'A dirty read'],
    1,
    'Postgres detects the cycle and kills one. Fix by always acquiring locks in a consistent order.'),
  q('pg-7', 'PostgreSQL',
    'Reads from a streaming replica may be stale because:',
    ['Replicas use different indexes', 'Replication is asynchronous by default, so there is lag', 'Replicas cache aggressively', 'Replicas run older Postgres'],
    1,
    'Read-your-own-writes breaks on a replica. Route reads that follow a write to the primary, or use synchronous commit for those paths.'),
  q('pg-8', 'PostgreSQL',
    'Adding a NOT NULL column with a default to a 500GB table in Postgres 11+:',
    ['Rewrites the whole table', 'Is a fast metadata-only operation', 'Requires downtime always', 'Is not allowed'],
    1,
    'Since 11 the default is stored in the catalog. On older versions it was a full rewrite — the classic expand-contract motivation.'),

  // ------------------------------------------------ SQL (assessment format)
  q('sql-1', 'SQL',
    'You need the total per customer, including customers with zero orders. Which join?',
    ['INNER JOIN customers to orders', 'LEFT JOIN from customers to orders, with COALESCE on the aggregate', 'RIGHT JOIN from customers', 'CROSS JOIN'],
    1,
    'The INNER JOIN silently drops the zero-order customers — the single most common wrong answer on SQL assessments. COALESCE turns the resulting NULL sum into 0.',
    'phase-0-online-assessments/04-sql-challenge-bank.md'),
  q('sql-2', 'SQL',
    'What is the difference between WHERE and HAVING?',
    ['None', 'WHERE filters rows before grouping; HAVING filters groups after aggregation', 'HAVING is faster', 'WHERE cannot be used with GROUP BY'],
    1,
    'So an aggregate condition like COUNT(*) > 3 must go in HAVING. Putting it in WHERE is a syntax error, and putting a row filter in HAVING needlessly aggregates rows you could have discarded.'),
  q('sql-3', 'SQL',
    'To number rows within each group by descending amount, you want:',
    ['GROUP BY with COUNT', 'ROW_NUMBER() OVER (PARTITION BY group_col ORDER BY amount DESC)', 'ORDER BY with LIMIT', 'A self join'],
    1,
    'Window functions are the highest-yield SQL topic on senior assessments and the one most backend engineers have never drilled. Know ROW_NUMBER vs RANK vs DENSE_RANK.'),
  q('sql-4', 'SQL',
    'RANK() and DENSE_RANK() differ how, on ties?',
    ['They are identical', 'RANK leaves gaps after a tie (1,1,3); DENSE_RANK does not (1,1,2)', 'DENSE_RANK leaves gaps', 'RANK cannot handle ties'],
    1,
    'Small detail, frequently the exact thing a test case checks.'),
  q('sql-5', 'SQL',
    '`SELECT * FROM t WHERE status != \'active\'` unexpectedly omits rows. Why?',
    ['The index is missing', 'Rows where status IS NULL do not satisfy the comparison — NULL comparisons yield UNKNOWN', 'Case sensitivity', '!= is invalid SQL'],
    1,
    'Three-valued logic. You need `status IS DISTINCT FROM \'active\'` or an explicit `OR status IS NULL`. A classic assessment trap.'),
  q('sql-6', 'SQL',
    'For a "second highest salary per department" question, the cleanest approach is:',
    ['Two nested subqueries with MAX', 'A CTE with DENSE_RANK() partitioned by department, then filter rank = 2', 'ORDER BY with OFFSET 1', 'A self join on salary'],
    1,
    'Reaches for the right tool and reads clearly. OFFSET 1 breaks with ties and does not partition by department.'),
  q('sql-7', 'SQL',
    'A query filtering on `WHERE DATE(created_at) = \'2026-08-11\'` is slow despite an index on created_at. Why?',
    ['The index is corrupt', 'Wrapping the column in a function prevents the index from being used — rewrite as a range predicate', 'DATE() is deprecated', 'The table is too small'],
    1,
    'Rewrite as `created_at >= \'2026-08-11\' AND created_at < \'2026-08-12\'`. This exact pattern appears in both SQL tests and real query-tuning interviews.'),

  // ------------------------------------------------ Redis & Caching
  q('redis-1', 'Redis & Caching',
    'A cache stampede happens when:',
    ['The cache is full', 'A hot key expires and thousands of concurrent requests all miss and hit the database at once', 'Redis restarts', 'TTLs are too long'],
    1,
    'Mitigations: probabilistic early expiry, a mutex/single-flight on recompute, or serving stale while refreshing.',
    'phase-3-databases-data/02-redis-deep-dive.md'),
  q('redis-2', 'Redis & Caching',
    'Cache penetration is best defended with:',
    ['Longer TTLs', 'Caching negative results (and/or a bloom filter of existing keys)', 'More replicas', 'Bigger instances'],
    1,
    'Penetration is repeated lookups for keys that do not exist, so every request reaches the database. Cache the miss with a short TTL.'),
  q('redis-3', 'Redis & Caching',
    'Why add jitter to cache TTLs?',
    ['To improve hit rate', 'To avoid an avalanche where a large set of keys expires simultaneously', 'To save memory', 'To simplify invalidation'],
    1,
    'Keys written in one warm-up batch expire in one batch. Randomising TTL by ±10% spreads the reload.'),
  q('redis-4', 'Redis & Caching',
    'Redlock is controversial mainly because:',
    ['It is slow', 'Its safety depends on bounded clock drift and GC pauses; fencing tokens are needed for correctness', 'It needs Redis Cluster', 'It is not open source'],
    1,
    'A lock holder that pauses past the lease can still write. A monotonic fencing token checked by the resource is the real fix.'),
  q('redis-5', 'Redis & Caching',
    'For rate limiting across many app instances, the correct Redis approach is:',
    ['INCR then EXPIRE as two commands', 'A Lua script performing the check and increment atomically', 'Per-instance in-memory counters', 'A SQL table'],
    1,
    'Two round trips leave a window where the key has no TTL. Lua makes the read-modify-write atomic.'),
  q('redis-6', 'Redis & Caching',
    'RDB vs AOF: which statement is right?',
    ['RDB loses nothing', 'RDB is a point-in-time snapshot (can lose recent writes); AOF logs every write and replays it', 'AOF is faster to load', 'They cannot be combined'],
    1,
    'Most production setups use both: AOF for durability, RDB for fast restarts and backups.'),
  q('redis-7', 'Redis & Caching',
    'Running `KEYS *` on a production Redis:',
    ['Is fine, it is O(1)', 'Blocks the single-threaded server while it scans every key', 'Returns only 100 keys', 'Is disabled by default'],
    1,
    'Use SCAN with a cursor. KEYS on a multi-million-key instance is a self-inflicted outage.'),

  // ------------------------------------------------ API Design
  q('api-1', 'API Design',
    'A client retries a POST /payments after a timeout. What prevents a double charge?',
    ['A unique constraint on amount', 'An idempotency key supplied by the client and stored server-side with the result', 'Rate limiting', 'HTTPS'],
    1,
    'The server stores key → result. A repeat with the same key returns the original response instead of re-executing.',
    'phase-2-apis-realtime-systems/02-rest-api-best-practices.md'),
  q('api-2', 'API Design',
    'Cursor pagination beats offset pagination mainly because:',
    ['It is simpler', 'Offset degrades on deep pages and skips/duplicates rows when data shifts', 'It supports sorting', 'It returns totals'],
    1,
    'OFFSET 100000 makes the database walk 100k rows. Cursors are stable under concurrent inserts.'),
  q('api-3', 'API Design',
    'Which status code fits "the request was well formed but the entity failed validation"?',
    ['400', '422', '409', '500'],
    1,
    '400 for malformed syntax, 422 for semantic validation failure, 409 for a state conflict. Being precise here is a small but real signal.'),
  q('api-4', 'API Design',
    'A webhook receiver should verify authenticity by:',
    ['Checking the source IP', 'Verifying an HMAC signature over the raw body with a shared secret, and rejecting stale timestamps', 'Requiring HTTPS only', 'Checking the user agent'],
    1,
    'The timestamp check is what prevents replay. Note that you must hash the RAW body, before JSON parsing.'),
  q('api-5', 'API Design',
    'The most common backwards-incompatible API change people make by accident is:',
    ['Adding an optional field', 'Making an optional request field required, or narrowing an enum', 'Adding an endpoint', 'Adding a response header'],
    1,
    'Additive changes are safe. Tightening validation or removing an enum value breaks existing clients silently.'),
  q('api-6', 'API Design',
    'GraphQL\'s biggest operational risk versus REST is:',
    ['Slower serialisation', 'Unbounded query cost — a deeply nested query can be a denial of service', 'No caching at all', 'No auth support'],
    1,
    'Mitigate with query depth limits, complexity analysis, and persisted queries.'),
  q('api-7', 'API Design',
    'gRPC is usually the right choice when:',
    ['Serving public browser clients', 'Internal service-to-service calls needing low latency, streaming and a strict contract', 'Serving static files', 'Webhook delivery'],
    1,
    'Browsers need gRPC-Web plus a proxy, so public-facing APIs usually stay REST or GraphQL.'),

  // ------------------------------------------------ Event-Driven Architecture
  q('eda-1', 'Event-Driven Architecture',
    'The dual-write problem is:',
    ['Writing to two databases', 'Writing to the database and publishing an event non-atomically, so one can succeed while the other fails', 'Duplicate consumers', 'Two producers on one topic'],
    1,
    'Outbox pattern or CDC solves it. This is one of the highest-signal questions for event-driven experience.',
    'phase-2-apis-realtime-systems/04-event-driven-architecture.md'),
  q('eda-2', 'Event-Driven Architecture',
    'With at-least-once delivery, consumers must be:',
    ['Fast', 'Idempotent', 'Single-threaded', 'Ordered'],
    1,
    'Redelivery is guaranteed to happen eventually. Dedupe on an event id, or make the effect naturally idempotent (upsert rather than insert).'),
  q('eda-3', 'Event-Driven Architecture',
    'Choreography vs orchestration for a saga: orchestration is preferable when',
    ['There are only two services', 'The workflow is complex and you need one place to see and change the process', 'You want maximum decoupling', 'Latency is critical'],
    1,
    'Choreography decouples but scatters the business process across services, making it hard to reason about and to compensate correctly.'),
  q('eda-4', 'Event-Driven Architecture',
    'A message lands in the dead letter queue. The FIRST thing to do is:',
    ['Delete it', 'Alert, inspect the failure reason, and decide replay vs discard — a silent DLQ is data loss', 'Replay immediately', 'Increase retries'],
    1,
    'An unmonitored DLQ is the most common way event-driven systems lose data quietly.'),
  q('eda-5', 'Event-Driven Architecture',
    'To evolve an event schema without breaking consumers you should:',
    ['Rename fields freely', 'Only make additive, optional changes and enforce compatibility with a schema registry', 'Version every event with a new topic', 'Broadcast a migration notice'],
    1,
    'Backward-compatible evolution plus registry enforcement. New required fields break old consumers.'),
  q('eda-6', 'Event-Driven Architecture',
    'Event sourcing\'s biggest real-world cost is:',
    ['Storage', 'Complexity of projections, schema evolution and replay — plus a much harder GDPR erasure story', 'Slow writes', 'No tooling'],
    1,
    'Immutable logs and the right to erasure are in tension; crypto-shredding is the usual answer.'),
  q('eda-7', 'Event-Driven Architecture',
    'Kafka guarantees ordering:',
    ['Across the whole topic', 'Within a single partition', 'Per consumer group', 'Per broker'],
    1,
    'So your partition key determines your ordering guarantee. Ordering per user means keying by user id.'),

  // ------------------------------------------------ Kafka & Messaging
  q('kafka-1', 'Kafka & Messaging',
    'Adding more consumers than partitions in a consumer group results in:',
    ['Faster processing', 'Idle consumers — a partition is assigned to at most one consumer in a group', 'Duplicate processing', 'A rebalance loop'],
    1,
    'Partition count is your parallelism ceiling. This is why partition planning matters up front.',
    'phase-3-databases-data/03-kafka-deep-dive.md'),
  q('kafka-2', 'Kafka & Messaging',
    'Kafka "exactly-once" requires:',
    ['Just enabling a flag', 'Idempotent producer + transactions + read_committed consumers, and the effects must stay inside Kafka or be idempotent', 'Manual dedupe only', 'A single partition'],
    1,
    'End-to-end exactly-once across an external database still needs idempotent writes or the outbox pattern. Qualifying this is the senior answer.'),
  q('kafka-3', 'Kafka & Messaging',
    'A consumer group rebalance is triggered by:',
    ['A new message', 'A member joining or leaving, or failing to heartbeat within session.timeout.ms', 'A broker restart only', 'Changing the offset'],
    1,
    'Long processing between polls exceeds max.poll.interval.ms, causing an eviction and a rebalance storm. A classic production incident.'),
  q('kafka-4', 'Kafka & Messaging',
    'RabbitMQ is a better fit than Kafka when:',
    ['You need to replay history', 'You need complex per-message routing, priorities and low-latency task queues', 'You have huge throughput', 'You need long retention'],
    1,
    'Kafka is a distributed log; Rabbit is a smart broker. Replay and retention favour Kafka; routing and per-message ack semantics favour Rabbit.'),
  q('kafka-5', 'Kafka & Messaging',
    'Committing offsets BEFORE processing gives you:',
    ['Exactly-once', 'At-most-once — a crash loses the message', 'At-least-once', 'Ordered delivery'],
    1,
    'Commit after processing for at-least-once. The choice is a data-loss versus duplicate-work trade-off; name it explicitly.'),
  q('kafka-6', 'Kafka & Messaging',
    'A partition\'s replication factor of 3 with min.insync.replicas=2 means:',
    ['Writes need all 3 replicas', 'Writes with acks=all succeed once 2 replicas have the record, tolerating one broker loss', 'Reads come from 2 replicas', 'Data is stored twice'],
    1,
    'With acks=all and min.insync=2 you survive one broker failure without data loss and without blocking writes.'),

  // ------------------------------------------------ Real-Time Systems
  q('rt-1', 'Real-Time Systems',
    'Scaling Socket.io beyond one instance requires:',
    ['Nothing', 'A Redis (or similar) adapter to broadcast across instances, plus sticky sessions for the HTTP long-poll handshake', 'More memory', 'HTTP/2'],
    1,
    'Without the adapter, a message emitted on instance A never reaches a client connected to instance B.',
    'phase-2-apis-realtime-systems/03-realtime-systems-agora.md'),
  q('rt-2', 'Real-Time Systems',
    'Server-Sent Events versus WebSockets: SSE is preferable when:',
    ['You need bidirectional communication', 'You only need server-to-client push and want automatic reconnect over plain HTTP', 'You need binary frames', 'You need sub-millisecond latency'],
    1,
    'SSE is simpler, works through most proxies, and reconnects with Last-Event-ID for free. It is the right default for LLM token streaming.'),
  q('rt-3', 'Real-Time Systems',
    'The main memory risk in a long-lived WebSocket server is:',
    ['Too many timers', 'Per-connection state and unbounded outbound buffers for slow consumers', 'JSON parsing', 'TLS handshakes'],
    1,
    'A slow client that cannot drain its socket grows a server-side buffer. Bound it and disconnect offenders.'),
  q('rt-4', 'Real-Time Systems',
    'For a live-streaming token service, tokens should be:',
    ['Long-lived and shared', 'Short-lived, per-user, per-channel, minted server-side with the app certificate never leaving the backend', 'Generated on the client', 'Static per app'],
    1,
    'Client-side generation leaks the certificate. Short TTLs bound the damage of a leaked token.'),
  q('rt-5', 'Real-Time Systems',
    'After a client reconnects, missed messages are best recovered by:',
    ['Resending everything', 'A cursor/sequence number the client sends on reconnect, so the server replays only the gap', 'Client-side polling', 'Ignoring the gap'],
    1,
    'Sequence numbers plus a bounded server-side backlog. This is the same pattern as Kafka offsets.'),

  // ------------------------------------------------ NoSQL
  q('nosql-1', 'NoSQL',
    'DynamoDB single-table design starts from:',
    ['Entity relationships', 'The list of access patterns', 'Normalisation rules', 'Index count'],
    1,
    'You model the queries, then shape the keys to serve them. Designing it relationally then adding indexes is the classic anti-pattern.',
    'phase-3-databases-data/05-nosql-mongodb-dynamodb.md'),
  q('nosql-2', 'NoSQL',
    'A DynamoDB hot partition is caused by:',
    ['Too many items', 'A partition key with low cardinality or heavily skewed traffic', 'Missing sort key', 'On-demand billing'],
    1,
    'Fix by adding a suffix/shard to the key, or choosing a higher-cardinality attribute.'),
  q('nosql-3', 'NoSQL',
    'MongoDB\'s document size limit is:',
    ['1 MB', '16 MB', '64 MB', 'Unbounded'],
    1,
    'Which is why unbounded arrays inside a document (the "massive array" anti-pattern) eventually break — use the outlier or bucket pattern.'),
  q('nosql-4', 'NoSQL',
    'CAP says that during a network partition you must choose between:',
    ['Consistency and performance', 'Consistency and availability', 'Availability and durability', 'Latency and throughput'],
    1,
    'And PACELC adds: even when there is no partition, you still trade latency against consistency. Bringing up PACELC scores points.',
    'phase-3-databases-data/08-database-architecture-fundamentals.md'),
  q('nosql-5', 'NoSQL',
    'A DynamoDB GSI differs from an LSI in that:',
    ['GSI is cheaper', 'A GSI has its own partition key and capacity and is eventually consistent; an LSI shares the table\'s partition key and can be strongly consistent', 'LSIs can be added later', 'GSIs are limited to 1'],
    1,
    'LSIs must be created with the table and share the 10GB item-collection limit — a real production constraint.'),

  // ------------------------------------------------ AWS
  q('aws-1', 'AWS',
    'The most effective fix for Lambda cold starts on a latency-sensitive path is:',
    ['More memory only', 'Provisioned concurrency, plus a smaller bundle and avoiding VPC-attached cold paths where possible', 'A longer timeout', 'More retries'],
    1,
    'Memory does help (it scales CPU) but provisioned concurrency directly removes the cold start for the reserved slots.',
    'phase-4-cloud-infrastructure/02-aws-serverless-deep-dive.md'),
  q('aws-2', 'AWS',
    'An unbounded Lambda fanout in front of an RDS instance typically fails because:',
    ['Lambda is slow', 'Concurrency spikes exhaust the database connection pool', 'IAM blocks it', 'S3 throttles'],
    1,
    'Use RDS Proxy, or a queue to bound concurrency with reserved concurrency limits.'),
  q('aws-3', 'AWS',
    'Which is the cheapest way to serve 1TB/month of static assets?',
    ['EC2 with NGINX', 'S3 behind CloudFront', 'Lambda@Edge', 'EFS'],
    1,
    'And CloudFront egress is cheaper than S3 egress — an easy cost-optimisation talking point.'),
  q('aws-4', 'AWS',
    'API Gateway HTTP APIs versus REST APIs: HTTP APIs are:',
    ['More featureful', 'Cheaper and lower latency, but without request validation, WAF integration and usage plans', 'Deprecated', 'Only for WebSockets'],
    1,
    'Know the trade-off — picking HTTP APIs to cut cost then needing usage plans is a common regret.'),
  q('aws-5', 'AWS',
    'For a Bangladeshi startup optimising AWS spend, the biggest wins usually come from:',
    ['Reserved instances only', 'Right-sizing, S3 lifecycle policies, NAT gateway removal, and moving spiky workloads to serverless', 'Switching regions', 'Turning off CloudWatch'],
    1,
    'NAT gateway charges surprise almost everyone. Being able to name specific line items is a strong signal.'),
  q('aws-6', 'AWS',
    'Step Functions is the right tool when:',
    ['You need a message queue', 'You need durable, visual orchestration of a multi-step workflow with retries and compensation', 'You need a cron job', 'You need caching'],
    1,
    'It is managed saga orchestration. Mentioning it as an alternative to a hand-rolled orchestrator is a good move.'),

  // ------------------------------------------------ Docker & Kubernetes
  q('k8s-1', 'Docker & Kubernetes',
    'Difference between a liveness and a readiness probe:',
    ['None', 'Liveness failure restarts the container; readiness failure removes it from service endpoints', 'Readiness restarts the pod', 'Liveness controls scaling'],
    1,
    'Getting this backwards causes restart loops during slow startups. Add a startup probe for slow-booting apps.',
    'phase-4-cloud-infrastructure/04-kubernetes-basics.md'),
  q('k8s-2', 'Docker & Kubernetes',
    'A rolling update can still drop requests because:',
    ['Kubernetes is buggy', 'Endpoint removal and SIGTERM race — the pod may stop before the load balancer stops sending traffic', 'Probes are disabled', 'Replicas are too high'],
    1,
    'Fix with a preStop sleep, correct terminationGracePeriod, and a graceful shutdown that drains in-flight requests.'),
  q('k8s-3', 'Docker & Kubernetes',
    'A pod is OOMKilled. The most likely cause is:',
    ['CPU limit too low', 'Memory usage exceeded the container memory limit', 'Node disk pressure', 'Too many replicas'],
    1,
    'For Node, also check that --max-old-space-size is set below the container limit.'),
  q('k8s-4', 'Docker & Kubernetes',
    'The main benefit of a multi-stage Dockerfile is:',
    ['Faster builds only', 'A small runtime image that excludes build tools and dev dependencies — smaller attack surface and faster pulls', 'Better logging', 'Automatic scaling'],
    1,
    'A 1.2GB image versus a 150MB image also changes your deploy time and your registry bill.'),
  q('k8s-5', 'Docker & Kubernetes',
    'Setting CPU limits (not just requests) on a latency-sensitive Node service can:',
    ['Improve latency', 'Cause CFS throttling and p99 latency spikes', 'Reduce memory', 'Disable HPA'],
    1,
    'A widely misunderstood behaviour. Many teams set requests but deliberately omit CPU limits for latency-critical services.'),
  q('k8s-6', 'Docker & Kubernetes',
    'Running a container as root in production is discouraged because:',
    ['It is slower', 'A container escape or a writable mount becomes a much larger blast radius', 'It breaks logging', 'Kubernetes forbids it'],
    1,
    'Set runAsNonRoot, a read-only root filesystem, and drop capabilities.'),

  // ------------------------------------------------ Observability
  q('obs-1', 'Observability',
    'An SLI is:',
    ['A promise to customers', 'A measured indicator of service behaviour, such as the proportion of requests served under 300ms', 'An alert threshold', 'A dashboard'],
    1,
    'SLI = the measurement. SLO = the target for it. SLA = the contractual promise with consequences.',
    'phase-4-cloud-infrastructure/05-observability-reliability.md'),
  q('obs-2', 'Observability',
    'Burn-rate alerting is better than static threshold alerting because:',
    ['It is simpler', 'It alerts on how fast you are consuming the error budget, catching both fast and slow burns with fewer false pages', 'It needs no SLO', 'It reduces logging cost'],
    1,
    'Multi-window multi-burn-rate alerts are the Google SRE standard and a strong thing to bring up unprompted.'),
  q('obs-3', 'Observability',
    'To trace a request across five microservices you need:',
    ['Correlated logs only', 'Context propagation of a trace id via headers, with spans exported to a collector', 'Bigger log retention', 'Synchronised clocks'],
    1,
    'OpenTelemetry is the vendor-neutral answer. Without propagation, per-service logs cannot be stitched together.'),
  q('obs-4', 'Observability',
    'Averaging latency hides:',
    ['Nothing', 'The tail — p99 users can be 10x slower while the mean looks fine', 'Throughput', 'Error rates'],
    1,
    'Always quote percentiles. And note that averaging pre-computed percentiles across instances is mathematically invalid.'),
  q('obs-5', 'Observability',
    'A blameless postmortem\'s primary purpose is:',
    ['Assigning responsibility', 'Finding the systemic conditions that allowed the failure, so the fix is a control not a person', 'Documenting for auditors', 'Justifying headcount'],
    1,
    'The framing matters: "why did the system make this error easy?" rather than "who typed the command".'),

  // ------------------------------------------------ Security
  q('sec-1', 'Security',
    'Why should PII never go in a JWT payload?',
    ['It makes the token large', 'JWT payloads are base64-encoded, not encrypted — anyone holding the token can read them', 'It breaks signing', 'It is not allowed by spec'],
    1,
    'Signed does not mean confidential. Use an opaque session id or JWE if you need confidentiality.',
    'phase-4-cloud-infrastructure/06-security-compliance.md'),
  q('sec-2', 'Security',
    'PKCE exists to protect:',
    ['Server-to-server calls', 'Public clients (mobile/SPA) from authorisation-code interception', 'Refresh tokens at rest', 'TLS handshakes'],
    1,
    'The code_verifier/code_challenge pair means a stolen code is useless without the verifier. Now recommended for all clients, not just public ones.'),
  q('sec-3', 'Security',
    'The correct defence against SQL injection is:',
    ['Escaping quotes', 'Parameterised queries / prepared statements', 'A WAF', 'Input length limits'],
    1,
    'ORMs give you this by default — until someone concatenates into a raw query. That is where it actually happens.'),
  q('sec-4', 'Security',
    'GDPR "right to erasure" is hardest to satisfy in:',
    ['A relational database', 'Immutable stores: event logs, backups, analytics warehouses and replicas', 'Redis', 'S3'],
    1,
    'Crypto-shredding — encrypt per subject and destroy the key — is the standard architectural answer.'),
  q('sec-5', 'Security',
    'RBAC versus ABAC: ABAC is needed when:',
    ['There are many users', 'Access depends on attributes of the request context, such as tenant, resource owner, time or location', 'You use OAuth', 'You have fewer than 10 roles'],
    1,
    'Role explosion ("admin_tenant_37_readonly") is the symptom that you needed ABAC.'),
  q('sec-6', 'Security',
    'Storing a password should use:',
    ['SHA-256', 'A slow, salted KDF such as bcrypt, scrypt or Argon2', 'MD5 with salt', 'AES encryption'],
    1,
    'Fast hashes are the vulnerability — they let an attacker try billions of candidates per second.'),
  q('sec-7', 'Security',
    'Secrets in environment variables are:',
    ['Perfectly safe', 'Better than in code, but still exposed via process listings, crash dumps and child processes — a secrets manager with rotation is better', 'Encrypted at rest', 'Unreadable by the app'],
    1,
    'The senior answer names the improvement path rather than declaring env vars fine or forbidden.'),

  // ------------------------------------------------ Distributed Systems
  q('ds-1', 'Distributed Systems',
    'A partitioned leader that still believes it is the leader can corrupt state unless:',
    ['It has a longer lease', 'The resource rejects writes with a stale fencing token', 'Clocks are synchronised', 'You use TCP'],
    1,
    'Fencing tokens are the correct answer. Leases and clock sync reduce the window but cannot close it.',
    'phase-5-system-design/03-distributed-systems.md'),
  q('ds-2', 'Distributed Systems',
    'Read-your-own-writes consistency can be provided on a replicated store by:',
    ['Using stronger hardware', 'Routing a user\'s reads to the primary (or to a replica known to have their write) for a period after the write', 'Caching more', 'Disabling replicas'],
    1,
    'Sticky routing or a write-timestamp token carried by the client. It is a session guarantee, not a global one.'),
  q('ds-3', 'Distributed Systems',
    'Vector clocks give you what Lamport clocks do not?',
    ['Wall-clock accuracy', 'The ability to detect concurrent (conflicting) events rather than only a total order', 'Lower storage', 'Faster comparison'],
    1,
    'Lamport gives a consistent ordering; vector clocks reveal causality and concurrency, which is what conflict resolution needs.'),
  q('ds-4', 'Distributed Systems',
    'Two-phase commit\'s core weakness is:',
    ['It is slow', 'The coordinator is a blocking single point of failure — participants can hold locks indefinitely', 'It needs three phases', 'It cannot span databases'],
    1,
    'Which is why saga with compensating transactions is the usual microservices answer.'),
  q('ds-5', 'Distributed Systems',
    'In a quorum system with N=3, W=2, R=2 you get:',
    ['Eventual consistency only', 'Strong consistency for reads, since W + R > N guarantees overlap', 'Higher availability than N=3, W=1', 'No fault tolerance'],
    1,
    'The overlap rule W + R > N is the thing to remember and it comes up constantly.'),
  q('ds-6', 'Distributed Systems',
    'A CRDT is useful when:',
    ['You need transactions', 'Concurrent replicas must merge automatically without coordination', 'You need strong consistency', 'Data is small'],
    1,
    'Collaborative editing and offline-first mobile sync are the canonical uses. The cost is metadata growth and restricted operations.'),

  // ------------------------------------------------ Architecture Patterns
  q('arch-1', 'Architecture Patterns',
    'The strongest argument for a modular monolith over microservices at a 12-person company is:',
    ['It is more modern', 'Distributed systems add operational and cognitive cost that only pays off past a certain team and scale threshold', 'It scales better', 'It is easier to test'],
    1,
    'Arguing for the monolith with good reasons impresses more than reflexively reaching for microservices.',
    'phase-5-system-design/02-architecture-patterns.md'),
  q('arch-2', 'Architecture Patterns',
    'The strangler fig pattern works by:',
    ['Rewriting everything then switching', 'Routing slices of traffic to new services behind a facade until the old system is dead', 'Freezing the monolith', 'Running both systems permanently'],
    1,
    'Incremental and reversible. The big-bang rewrite is the failure mode it exists to avoid.'),
  q('arch-3', 'Architecture Patterns',
    'CQRS is justified when:',
    ['You have a lot of code', 'Read and write workloads have genuinely different shapes, scale or models', 'You use microservices', 'You need transactions'],
    1,
    'Applying CQRS everywhere doubles the model count for no benefit. Say when you would NOT use it.'),
  q('arch-4', 'Architecture Patterns',
    'A circuit breaker\'s half-open state exists to:',
    ['Log errors', 'Probe recovery with a limited number of trial requests before fully reopening', 'Slow traffic', 'Buffer requests'],
    1,
    'Without half-open you either flood a recovering dependency or stay closed forever.'),
  q('arch-5', 'Architecture Patterns',
    'A BFF (backend for frontend) is introduced primarily to:',
    ['Reduce services', 'Give each client type a tailored aggregation layer so the shared API is not distorted by one client\'s needs', 'Improve caching', 'Replace the API gateway'],
    1,
    'The cost is another deployable per client. Name it.'),
  q('arch-6', 'Architecture Patterns',
    'Conway\'s Law implies that:',
    ['Code should be modular', 'Your architecture will mirror your communication structure, so team boundaries should be chosen deliberately', 'Teams should be small', 'Documentation matters'],
    1,
    'The inverse manoeuvre — reorganising teams to get the architecture you want — is a genuinely lead-level move to cite.'),

  // ------------------------------------------------ DDD & Data
  q('ddd-1', 'DDD & Data',
    'An aggregate boundary should be drawn around:',
    ['A database table', 'The set of objects that must stay transactionally consistent together', 'A microservice', 'A bounded context'],
    1,
    'One transaction per aggregate; between aggregates use eventual consistency via domain events.',
    'phase-5-system-design/04-ddd-and-data-architecture.md'),
  q('ddd-2', 'DDD & Data',
    'An anti-corruption layer exists to:',
    ['Encrypt data', 'Keep another context\'s model from leaking into and distorting yours', 'Validate input', 'Cache responses'],
    1,
    'Especially important when integrating a legacy system or a third-party API.'),
  q('ddd-3', 'DDD & Data',
    'Domain events differ from integration events in that:',
    ['They are faster', 'Domain events are internal to a bounded context; integration events are a published contract for other contexts', 'Domain events use Kafka', 'There is no difference'],
    1,
    'Publishing your internal domain events directly to other teams couples them to your model — a very common mistake.'),
  q('ddd-4', 'DDD & Data',
    'CDC with Debezium is preferable to dual writes because:',
    ['It is cheaper', 'It derives events from the committed transaction log, so the event cannot disagree with the database state', 'It is faster', 'It needs no broker'],
    1,
    'Same guarantee as the outbox pattern, achieved without changing application code.'),
  q('ddd-5', 'DDD & Data',
    'In stream processing, a watermark is:',
    ['A security marker', 'A heuristic for how far event time has advanced, used to decide when a window can close despite late data', 'A checkpoint', 'A partition key'],
    1,
    'Late data after the watermark needs an explicit policy: drop, side output, or update the result.'),

  // ------------------------------------------------ Reliability & Cost
  q('rel-1', 'Reliability & Cost',
    'An error budget is:',
    ['A financial allocation', 'The allowed unreliability implied by your SLO — for a 99.9% SLO, about 43 minutes of failure per month', 'A retry limit', 'An SLA penalty'],
    1,
    'It converts reliability into a currency you can trade against feature velocity, which is the whole point.',
    'phase-5-system-design/05-reliability-security-cost.md'),
  q('rel-2', 'Reliability & Cost',
    'RPO versus RTO:',
    ['They are the same', 'RPO is how much data you can afford to lose; RTO is how long you can be down', 'RPO is for backups only', 'RTO applies to databases only'],
    1,
    'A 5-minute RPO with hourly backups is incoherent. Interviewers use this to check you have actually planned DR.'),
  q('rel-3', 'Reliability & Cost',
    'Graceful degradation in a feed service means:',
    ['Returning a 503', 'Serving a slightly stale or less personalised feed when the ranking service is down, instead of failing', 'Retrying forever', 'Scaling up'],
    1,
    'Deciding in advance which features are sheddable is a design activity, not an incident-time decision.'),
  q('rel-4', 'Reliability & Cost',
    'Chaos engineering\'s prerequisite is:',
    ['A large team', 'Good observability and a hypothesis — otherwise you are just breaking production', 'Kubernetes', 'A staging environment'],
    1,
    'Start in staging with a steady-state hypothesis and a blast-radius limit.'),
  q('rel-5', 'Reliability & Cost',
    'Naive retries during a partial outage often cause:',
    ['Faster recovery', 'A retry storm that amplifies load and prevents recovery', 'Lower latency', 'Nothing'],
    1,
    'Exponential backoff with jitter, a retry budget, and a circuit breaker. Retrying a non-idempotent call is a second, worse bug.'),
  q('rel-6', 'Reliability & Cost',
    'The most common source of surprise AWS cost in a small startup is:',
    ['Lambda invocations', 'Data transfer — NAT gateways, cross-AZ traffic and egress', 'S3 storage', 'CloudWatch dashboards'],
    1,
    'Naming specific line items marks you as someone who has actually held a budget.'),

  // ------------------------------------------------ AI & LLM
  q('llm-1', 'AI & LLM',
    'In a RAG pipeline, the most common cause of bad answers is:',
    ['Model size', 'Retrieval quality — wrong chunking, poor embeddings or no reranking', 'Temperature', 'Prompt length'],
    1,
    'Generation quality is bounded by what you retrieve. Fix retrieval before touching the model.',
    'phase-2-apis-realtime-systems/06-ai-llm-integrations.md'),
  q('llm-2', 'AI & LLM',
    'The standard transport for streaming LLM tokens to a browser is:',
    ['WebSockets', 'Server-Sent Events', 'Long polling', 'gRPC-Web'],
    1,
    'One-directional, works over plain HTTP, reconnects for free. WebSockets are overkill unless you need client-to-server streaming too.'),
  q('llm-3', 'AI & LLM',
    'pgvector is attractive versus a dedicated vector database because:',
    ['It is faster at every scale', 'You keep one datastore, with transactional consistency between vectors and relational metadata', 'It has no index limits', 'It is the only option'],
    1,
    'Dedicated stores win at very large scale and on advanced filtering; below a few million vectors, one Postgres is usually the better engineering call.'),
  q('llm-4', 'AI & LLM',
    'The most effective lever on per-conversation LLM cost is usually:',
    ['A cheaper model only', 'Controlling context size — retrieval limits, summarised history, and caching repeated prefixes', 'Lower temperature', 'Fewer users'],
    1,
    'Input tokens dominate in RAG workloads. Prompt caching and tighter retrieval often beat swapping models.'),
  q('llm-5', 'AI & LLM',
    'Before shipping an LLM feature, the thing most teams skip and regret is:',
    ['Fine-tuning', 'An evaluation set with regression tests, so prompt or model changes are measurable', 'A vector database', 'A bigger context window'],
    1,
    'Without evals, every prompt change is a blind deploy. Being the person who insists on this is a strong differentiator.'),
  q('llm-6', 'AI & LLM',
    'The main backend risk of exposing tool-calling to an LLM is:',
    ['Latency', 'The model can be steered by injected content into invoking tools with attacker-chosen arguments', 'Token cost', 'Streaming complexity'],
    1,
    'Treat model output as untrusted input: validate arguments, scope permissions per tool, and require confirmation for destructive actions.'),
];
