/**
 * Skills matrix.
 *
 * `demand` is my read, as a hiring manager, of how often this skill is an
 * explicit requirement or a scored interview dimension for Senior/Lead Node
 * backend roles in the two target markets, on a 1-5 scale.
 *
 * `assumed` is the starting self-rating seeded from the candidate's repo and
 * work history — he re-rates everything himself on day 1, and the app scores
 * the gap as (demand - level) * demand so high-demand weaknesses float to the top.
 */
export interface SkillSeed {
  id: string;
  name: string;
  category: string;
  demandBD: number;
  demandRemote: number;
  assumed: number;
  why: string;
  proveIt: string;
  ref: string;
}

export const skills: SkillSeed[] = [
  // ---------------------------------------------------------- language & runtime
  {
    id: 'typescript-depth',
    name: 'TypeScript (advanced types)',
    category: 'Language & Runtime',
    demandBD: 4,
    demandRemote: 5,
    assumed: 4,
    why: 'Every serious Node job posting in 2026 says TypeScript. Generics, conditional types and discriminated unions are what separate "writes TS" from "designs TS APIs".',
    proveIt: 'Be able to write a generic repository type and explain why a discriminated union beats optional fields for a result type.',
    ref: 'phase-1-core-programming/01-javascript-typescript-deep-dive.md',
  },
  {
    id: 'node-internals',
    name: 'Node.js internals (event loop, streams, workers)',
    category: 'Language & Runtime',
    demandBD: 5,
    demandRemote: 5,
    assumed: 4,
    why: 'The single most reliable filter question for a Node senior. Phase order, microtask draining, and when to reach for worker threads.',
    proveIt: 'Explain what happens to 10k open sockets when one handler does a 200ms CPU-bound loop, and how you would fix it.',
    ref: 'phase-1-core-programming/02-nodejs-fundamentals.md',
  },
  {
    id: 'nestjs',
    name: 'NestJS (DI, pipeline, microservices)',
    category: 'Language & Runtime',
    demandBD: 4,
    demandRemote: 3,
    assumed: 5,
    why: 'Strong in the BD market and in EU agencies. Lower demand in US startups, which skew to Express/Fastify — do not lead with the framework there, lead with the architecture.',
    proveIt: 'Guard vs interceptor vs pipe, and the cost of request-scoped providers.',
    ref: 'phase-1-core-programming/03-nestjs-mastery.md',
  },
  {
    id: 'testing',
    name: 'Testing strategy (unit, integration, contract)',
    category: 'Language & Runtime',
    demandBD: 3,
    demandRemote: 5,
    assumed: 3,
    why: 'Take-home assignments are graded on tests more than on features. This is where BD candidates most often lose remote offers.',
    proveIt: 'A take-home repo with meaningful integration tests using testcontainers, plus a README explaining what you chose not to test.',
    ref: 'phase-1-core-programming/04-testing-and-quality.md',
  },

  // ---------------------------------------------------------- problem solving
  {
    id: 'dsa-patterns',
    name: 'DSA pattern recognition under time',
    category: 'Problem Solving',
    demandBD: 3,
    demandRemote: 5,
    assumed: 2,
    why: 'The online assessment is the gate you cannot talk your way through. This is the highest-leverage gap for an experienced architect.',
    proveIt: 'Two mediums solved in under 45 minutes total, cold, with clean code and stated complexity.',
    ref: 'practice',
  },
  {
    id: 'sql-assessment',
    name: 'SQL under assessment conditions',
    category: 'Problem Solving',
    demandBD: 4,
    demandRemote: 4,
    assumed: 3,
    why: 'The highest points-per-minute section on any mixed screening test, and the one backend engineers most often skip because they "use an ORM". Window functions and cohort queries are where candidates separate.',
    proveIt: 'Write a second-highest-per-group query with DENSE_RANK and a 30-day retention cohort query, cold, without looking anything up.',
    ref: 'phase-0-online-assessments/04-sql-challenge-bank.md',
  },
  {
    id: 'assessment-platforms',
    name: 'Assessment platform fluency',
    category: 'Problem Solving',
    demandBD: 3,
    demandRemote: 5,
    assumed: 1,
    why: 'Knowing how HackerRank scores partial output, how the Node stdin harness works, and how CodeSignal grows a spec across four levels is worth more marks than one extra algorithm pattern. Pure format knowledge, entirely learnable in an afternoon.',
    proveIt: 'Complete one full-length timed mock on each of the two platforms your target companies actually use.',
    ref: 'phase-0-online-assessments/00-platform-playbook.md',
  },
  {
    id: 'video-screen',
    name: 'One-way video screens (Talview / HireVue)',
    category: 'Leadership',
    demandBD: 2,
    demandRemote: 4,
    assumed: 1,
    why: 'Arrives early in the remote funnel, gets no second take, and is scored partly on delivery rather than content. A bad setup loses the round before anyone hears your answer.',
    proveIt: 'A recorded 90-second answer with good lighting, clean audio, and a structured response you would be happy for a stranger to watch.',
    ref: 'phase-0-online-assessments/07-video-interview-and-psychometric.md',
  },
  {
    id: 'js-practicals',
    name: 'JS/Node practical implementations',
    category: 'Problem Solving',
    demandBD: 4,
    demandRemote: 5,
    assumed: 3,
    why: 'Implement an async pool, an idempotency store, a batcher. Far more predictive of the job than DP, and almost nobody drills it.',
    proveIt: 'Write asyncPool with correct ordering and no batch-stalling, first try, in 15 minutes.',
    ref: 'practice?pattern=Node%20Practical',
  },

  // ---------------------------------------------------------- data
  {
    id: 'postgres',
    name: 'PostgreSQL (indexing, MVCC, query plans)',
    category: 'Data',
    demandBD: 5,
    demandRemote: 5,
    assumed: 4,
    why: 'Universal. Expect a real slow query on screen and "what would you do".',
    proveIt: 'Read an EXPLAIN ANALYZE out loud and name the fix plus its write-side cost.',
    ref: 'phase-3-databases-data/01-postgresql-deep-dive.md',
  },
  {
    id: 'redis',
    name: 'Redis & caching failure modes',
    category: 'Data',
    demandBD: 5,
    demandRemote: 4,
    assumed: 4,
    why: 'Cache-aside is table stakes; stampede, penetration and avalanche handling is the senior signal.',
    proveIt: 'Describe what happens to your database the moment Redis fails over, and the three mitigations.',
    ref: 'phase-3-databases-data/02-redis-deep-dive.md',
  },
  {
    id: 'kafka',
    name: 'Kafka / event streaming',
    category: 'Data',
    demandBD: 3,
    demandRemote: 4,
    assumed: 4,
    why: 'Your telecom-scale experience here is a genuine differentiator — most BD candidates have only used it as a queue.',
    proveIt: 'Explain exactly what "exactly-once" requires on both producer and consumer side, and when you would not use Kafka.',
    ref: 'phase-3-databases-data/03-kafka-deep-dive.md',
  },
  {
    id: 'nosql',
    name: 'DynamoDB / MongoDB modelling',
    category: 'Data',
    demandBD: 3,
    demandRemote: 4,
    assumed: 3,
    why: 'AWS-heavy remote roles will test access-pattern-first single-table design. Modelling Dynamo relationally is an instant no.',
    proveIt: 'Design a single-table schema for a given set of access patterns, with GSI choices justified.',
    ref: 'phase-3-databases-data/05-nosql-mongodb-dynamodb.md',
  },
  {
    id: 'migrations',
    name: 'Zero-downtime schema evolution',
    category: 'Data',
    demandBD: 3,
    demandRemote: 4,
    assumed: 3,
    why: 'A lead is expected to know expand-contract cold. It comes up as "how do you rename a column on a live 200GB table".',
    proveIt: 'Walk the six steps of expand-contract without notes.',
    ref: 'phase-3-databases-data/06-database-migrations-schema-evolution.md',
  },

  // ---------------------------------------------------------- architecture
  {
    id: 'system-design-hld',
    name: 'System design (HLD) under a 45-min clock',
    category: 'Architecture',
    demandBD: 4,
    demandRemote: 5,
    assumed: 3,
    why: 'The round that decides senior vs lead, and the one most affected by pacing rather than knowledge.',
    proveIt: 'Requirements + capacity math inside the first 8 minutes, every time.',
    ref: 'phase-5-system-design/06-hld-practice-problems.md',
  },
  {
    id: 'lld',
    name: 'Low-level design / OOD',
    category: 'Architecture',
    demandBD: 3,
    demandRemote: 4,
    assumed: 3,
    why: 'Common in EU and product companies as a 60-minute "design and code this class hierarchy" round.',
    proveIt: 'Design a rate limiter or parking lot with clean interfaces and a stated extension point.',
    ref: 'phase-5-system-design/07-lld-practice-problems.md',
  },
  {
    id: 'eda',
    name: 'Event-driven architecture (outbox, saga, idempotency)',
    category: 'Architecture',
    demandBD: 4,
    demandRemote: 5,
    assumed: 4,
    why: 'Your strongest differentiator. Concrete production stories here outrank any textbook answer.',
    proveIt: 'Tell the story of a duplicate you actually had to handle, and the fix you shipped.',
    ref: 'phase-2-apis-realtime-systems/04-event-driven-architecture.md',
  },
  {
    id: 'distributed-systems',
    name: 'Distributed systems theory',
    category: 'Architecture',
    demandBD: 2,
    demandRemote: 4,
    assumed: 3,
    why: 'Rarely asked directly in BD, frequently probed in remote senior loops via consistency and partition scenarios.',
    proveIt: 'Answer "your leader is partitioned but still thinks it leads — what breaks and how do you prevent it?" (fencing tokens).',
    ref: 'phase-5-system-design/03-distributed-systems.md',
  },
  {
    id: 'api-design',
    name: 'API design (REST, GraphQL, gRPC)',
    category: 'Architecture',
    demandBD: 4,
    demandRemote: 5,
    assumed: 4,
    why: 'Versioning, pagination and idempotency come up in nearly every backend loop.',
    proveIt: 'Design a payment endpoint and bring up idempotency keys before being asked.',
    ref: 'phase-2-apis-realtime-systems/02-rest-api-best-practices.md',
  },
  {
    id: 'realtime',
    name: 'Real-time systems (WebSockets, streaming)',
    category: 'Architecture',
    demandBD: 3,
    demandRemote: 3,
    assumed: 5,
    why: 'Niche but memorable. When it matches the role it is a near-instant shortlist.',
    proveIt: 'Explain scaling Socket.io past one instance, and what still breaks after the Redis adapter.',
    ref: 'phase-2-apis-realtime-systems/03-realtime-systems-agora.md',
  },

  // ---------------------------------------------------------- platform
  {
    id: 'aws',
    name: 'AWS (Lambda, API Gateway, AppSync, cost)',
    category: 'Platform',
    demandBD: 4,
    demandRemote: 5,
    assumed: 4,
    why: 'Cloud is assumed. Cost fluency is the differentiator, especially for bootstrapped startups.',
    proveIt: 'Estimate the monthly bill for a design and offer a cheaper shape.',
    ref: 'phase-4-cloud-infrastructure/02-aws-serverless-deep-dive.md',
  },
  {
    id: 'docker-k8s',
    name: 'Docker & Kubernetes',
    category: 'Platform',
    demandBD: 4,
    demandRemote: 4,
    assumed: 3,
    why: 'Not expected at SRE depth, but probes vs OOMKills vs rolling-update request loss are fair game for a lead.',
    proveIt: 'Explain why a rolling update can still drop requests, and the three fixes.',
    ref: 'phase-4-cloud-infrastructure/04-kubernetes-basics.md',
  },
  {
    id: 'observability',
    name: 'Observability & SLOs',
    category: 'Platform',
    demandBD: 3,
    demandRemote: 5,
    assumed: 3,
    why: 'The fastest way to prove you have RUN a system rather than only built one.',
    proveIt: 'State one SLI, its SLO, and what you actually did when the error budget burned.',
    ref: 'phase-4-cloud-infrastructure/05-observability-reliability.md',
  },
  {
    id: 'cicd',
    name: 'CI/CD & IaC',
    category: 'Platform',
    demandBD: 4,
    demandRemote: 4,
    assumed: 3,
    why: 'Leads own the pipeline. Expect questions on deployment safety and rollback.',
    proveIt: 'Describe your rollback story and how long it takes end to end.',
    ref: 'phase-4-cloud-infrastructure/08-cicd-devops.md',
  },
  {
    id: 'security',
    name: 'Security & compliance (OAuth2, GDPR, SOC 2)',
    category: 'Platform',
    demandBD: 3,
    demandRemote: 5,
    assumed: 3,
    why: 'For EU/US clients a single wrong answer on data residency or token handling can end a loop.',
    proveIt: 'Explain PKCE and why PII never goes in a JWT.',
    ref: 'phase-4-cloud-infrastructure/06-security-compliance.md',
  },

  // ---------------------------------------------------------- 2026 edge
  {
    id: 'llm-integration',
    name: 'LLM integration & RAG backends',
    category: '2026 Edge',
    demandBD: 3,
    demandRemote: 5,
    assumed: 2,
    why: 'A large and growing share of remote backend postings mention it. Backend engineers who have shipped RAG with real cost and eval controls are scarce and priced accordingly. Biggest single upside item on this list.',
    proveIt: 'Ship one small RAG service: ingestion, chunking, pgvector, streaming responses, an eval harness, and a cost-per-conversation number.',
    ref: 'phase-2-apis-realtime-systems/06-ai-llm-integrations.md',
  },
  {
    id: 'cost-engineering',
    name: 'Cost engineering / FinOps',
    category: '2026 Edge',
    demandBD: 4,
    demandRemote: 4,
    assumed: 3,
    why: 'Underrated everywhere, decisive in the BD market and in bootstrapped remote startups.',
    proveIt: 'One story where you cut spend by a stated percentage without hurting reliability.',
    ref: 'phase-5-system-design/05-reliability-security-cost.md',
  },

  // ---------------------------------------------------------- leadership
  {
    id: 'technical-writing',
    name: 'ADRs, RFCs & technical writing',
    category: 'Leadership',
    demandBD: 2,
    demandRemote: 5,
    assumed: 3,
    why: 'In async remote teams, writing IS the job. It is also the cheapest proof of lead-level judgment you can hand an interviewer.',
    proveIt: 'One real ADR from your own history, one page, ready to share.',
    ref: 'phase-5-system-design/08-architect-level-practice.md',
  },
  {
    id: 'english-communication',
    name: 'Spoken English under technical pressure',
    category: 'Leadership',
    demandBD: 2,
    demandRemote: 5,
    assumed: 3,
    why: 'The number one gatekeeper for international remote roles, ahead of any technical dimension. Fluency matters less than structure: signposting, pausing, and checking in.',
    proveIt: 'A recorded 5-minute architecture walkthrough you would be happy for a stranger to hear.',
    ref: 'behavioral',
  },
  {
    id: 'mentoring',
    name: 'Mentoring & code review leadership',
    category: 'Leadership',
    demandBD: 4,
    demandRemote: 4,
    assumed: 4,
    why: 'The lead title is largely bought with evidence of raising other people\'s output.',
    proveIt: 'A story with a measurable team outcome, not just "I mentored juniors".',
    ref: 'behavioral',
  },
  {
    id: 'incident-command',
    name: 'Incident response & postmortems',
    category: 'Leadership',
    demandBD: 3,
    demandRemote: 5,
    assumed: 4,
    why: 'Detection, mitigation, root cause, systemic fix. Naming your own mistake reads as senior, not weak.',
    proveIt: 'One incident story with timestamps and a systemic (not heroic) fix.',
    ref: 'phase-4-cloud-infrastructure/05-observability-reliability.md',
  },
  {
    id: 'negotiation',
    name: 'Compensation negotiation',
    category: 'Leadership',
    demandBD: 3,
    demandRemote: 5,
    assumed: 2,
    why: 'Not a hiring criterion — a personal-outcome skill. The most common BD mistake in remote loops is naming a number first, anchored to local salary.',
    proveIt: 'Three scripted responses ready: they ask first, they lowball on geography, they ask your current salary.',
    ref: 'playbook#negotiation',
  },
];
